import { useEffect, useState, type FormEvent } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { Boxes, LayoutDashboard, ShoppingCart, ArrowLeftRight, ClipboardCheck, ShieldCheck, Menu, X, Plus, Search, Bell, ChevronRight, TrendingUp, TrendingDown } from 'lucide-react';

type Metrics={opening:number;closing:number;purchases:number;transferIn:number;transferOut:number;assigned:number;expended:number};
type Row={id:string;date:string;asset:string;type:string;base?:string;from?:string;to?:string;quantity:number;reference:string;assignee?:string;status?:string};
const fmt=(n:number)=>new Intl.NumberFormat().format(n);
const demo={metrics:{opening:12450,closing:13984,purchases:2180,transferIn:640,transferOut:485,assigned:3275,expended:801}, purchases:[{id:'1',date:'2026-09-24',asset:'5.56mm Ammunition',type:'Ammunition',base:'Fort Alpha',quantity:1200,reference:'PO-2026-1042'},{id:'2',date:'2026-09-21',asset:'Tactical Vehicle',type:'Vehicle',base:'Camp Bravo',quantity:8,reference:'PO-2026-1039'},{id:'3',date:'2026-09-18',asset:'M4 Carbine',type:'Weapon',base:'Fort Alpha',quantity:45,reference:'PO-2026-1028'}],transfers:[{id:'1',date:'2026-09-26',asset:'M4 Carbine',type:'Weapon',from:'Fort Alpha',to:'Camp Bravo',quantity:20,reference:'TR-26091',status:'Completed'},{id:'2',date:'2026-09-25',asset:'Night Vision Device',type:'Equipment',from:'Depot Central',to:'Fort Alpha',quantity:35,reference:'TR-26088',status:'In transit'},{id:'3',date:'2026-09-23',asset:'5.56mm Ammunition',type:'Ammunition',from:'Camp Bravo',to:'Fort Alpha',quantity:500,reference:'TR-26076',status:'Completed'}],assignments:[{id:'1',date:'2026-09-25',asset:'M4 Carbine',type:'Weapon',base:'Fort Alpha',quantity:12,reference:'AS-4018',assignee:'1st Infantry Platoon',status:'Assigned'},{id:'2',date:'2026-09-24',asset:'5.56mm Ammunition',type:'Ammunition',base:'Camp Bravo',quantity:240,reference:'EX-3091',assignee:'Range Training',status:'Expended'}]};
function useData(){const [data,setData]=useState(demo);useEffect(()=>{fetch('/api/dashboard').then(r=>r.ok?r.json():Promise.reject()).then(d=>setData(x=>({...x,metrics:d}))).catch(()=>{})},[]);return data}

const nav=[['/','Dashboard',LayoutDashboard],['/purchases','Purchases',ShoppingCart],['/transfers','Transfers',ArrowLeftRight],['/assignments','Assignments & Expenditures',ClipboardCheck],['/audit','Audit Log',ShieldCheck]] as const;
function App(){const [open,setOpen]=useState(false);return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="crest"><ShieldCheck/></div><div><b>ASSET COMMAND</b><small>LOGISTICS CONTROL</small></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon/>{label}</NavLink>)}</nav><div className="secure"><ShieldCheck/><div><b>SECURE SYSTEM</b><small>All activity is monitored</small></div></div><div className="profile"><span>JD</span><div><b>James Dalton</b><small>Administrator</small></div></div></aside><main><header><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div className="headerTitle"><b>Military Asset Management</b><small>Operational overview and logistics control</small></div><div className="headerActions"><button><Bell/></button><span className="classification">RESTRICTED</span></div></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/purchases" element={<RecordsPage kind="purchases"/>}/><Route path="/transfers" element={<RecordsPage kind="transfers"/>}/><Route path="/assignments" element={<RecordsPage kind="assignments"/>}/><Route path="/audit" element={<Audit/>}/></Routes></main></div>}

function Filters(){return <div className="filters"><label>Date range<input type="date" defaultValue="2026-09-01"/></label><label>Base<select><option>All bases</option><option>Fort Alpha</option><option>Camp Bravo</option><option>Depot Central</option></select></label><label>Equipment type<select><option>All equipment</option><option>Weapon</option><option>Vehicle</option><option>Ammunition</option><option>Equipment</option></select></label><button className="secondary"><Search/> Apply filters</button></div>}
function Dashboard(){const {metrics:m,purchases,transfers}=useData();const [modal,setModal]=useState(false);const net=m.purchases+m.transferIn-m.transferOut;return <section className="page"><div className="pageHead"><div><p className="eyebrow">COMMAND OVERVIEW</p><h1>Dashboard</h1><p>Inventory position across all operational bases</p></div><span className="updated">● LIVE DATA · Updated just now</span></div><Filters/><div className="metrics"><Metric label="Opening Balance" value={m.opening} hint="At start of period"/><Metric label="Closing Balance" value={m.closing} hint="Current inventory" accent/><button className="metric clickable" onClick={()=>setModal(true)}><span>Net Movement</span><strong>+{fmt(net)}</strong><small><TrendingUp/> Purchases + transfers <ChevronRight/></small></button><Metric label="Assigned" value={m.assigned} hint="In active deployment"/><Metric label="Expended" value={m.expended} hint="This period" danger/></div><div className="grid2"><Panel title="Recent purchases" link="/purchases"><Table rows={purchases}/></Panel><Panel title="Recent transfers" link="/transfers"><Table rows={transfers}/></Panel></div>{modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><p className="eyebrow">MOVEMENT BREAKDOWN</p><h2>Net Movement</h2></div><button onClick={()=>setModal(false)}><X/></button></div><div className="movement"><div><ShoppingCart/><span>Purchases</span><strong>+{fmt(m.purchases)}</strong></div><div><TrendingUp/><span>Transfer In</span><strong>+{fmt(m.transferIn)}</strong></div><div><TrendingDown/><span>Transfer Out</span><strong className="negative">−{fmt(m.transferOut)}</strong></div></div><div className="net"><span>Net Movement</span><strong>+{fmt(net)}</strong></div></div></div>}</section>}
function Metric({label,value,hint,accent,danger}:{label:string,value:number,hint:string,accent?:boolean,danger?:boolean}){return <div className={'metric '+(accent?'accent ':'')+(danger?'danger':'')}><span>{label}</span><strong>{fmt(value)}</strong><small>{hint}</small></div>}
function Panel({title,link,children}:{title:string;link:string;children:React.ReactNode}){return <div className="panel"><div className="panelHead"><h2>{title}</h2><NavLink to={link}>View all <ChevronRight/></NavLink></div>{children}</div>}
function Table({rows}:{rows:Row[]}){return <div className="tableWrap"><table><thead><tr><th>Date / Ref</th><th>Asset</th><th>Route / Base</th><th>Qty</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}<small>{r.reference}</small></td><td><b>{r.asset}</b><small>{r.type}</small></td><td>{r.base??`${r.from} → ${r.to}`}</td><td><b>{fmt(r.quantity)}</b></td><td>{r.status&&<span className={'badge '+r.status.toLowerCase().replace(' ','')}>{r.status}</span>}</td></tr>)}</tbody></table></div>}
function RecordsPage({kind}:{kind:'purchases'|'transfers'|'assignments'}){const data=demo[kind];const names={purchases:['Purchases','Record and review asset procurement','Record purchase'],transfers:['Asset Transfers','Move inventory between operational bases','New transfer'],assignments:['Assignments & Expenditures','Track deployed and consumed assets','New record']}[kind];const [show,setShow]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setShow(false)};return <section className="page"><div className="pageHead"><div><p className="eyebrow">LOGISTICS OPERATIONS</p><h1>{names[0]}</h1><p>{names[1]}</p></div><button className="primary" onClick={()=>setShow(true)}><Plus/>{names[2]}</button></div><Filters/><div className="panel"><div className="panelHead"><h2>Transaction history</h2><span className="count">{data.length} records</span></div><Table rows={data}/></div>{show&&<div className="overlay"><form className="modal form" onSubmit={submit}><div className="modalHead"><h2>{names[2]}</h2><button type="button" onClick={()=>setShow(false)}><X/></button></div><label>Asset<select required><option value="">Select asset</option><option>M4 Carbine</option><option>Tactical Vehicle</option><option>5.56mm Ammunition</option></select></label><div className="formRow"><label>{kind==='transfers'?'From base':'Base'}<select required><option>Fort Alpha</option><option>Camp Bravo</option></select></label>{kind==='transfers'&&<label>To base<select required><option>Camp Bravo</option><option>Depot Central</option></select></label>}</div>{kind==='assignments'&&<label>Assignee / Purpose<input required placeholder="Unit, person, or operation"/></label>}<label>Quantity<input type="number" min="1" required/></label><label>Reference<input placeholder="Official reference number"/></label><button className="primary" type="submit">Submit transaction</button></form></div>}</section>}
function Audit(){const events=[['09:42:18','TRANSFER_CREATED','TR-26091','James Dalton','Fort Alpha → Camp Bravo'],['09:31:04','PURCHASE_CREATED','PO-2026-1042','Maya Chen','1,200 × 5.56mm Ammunition'],['08:52:46','EXPENDITURE_RECORDED','EX-3091','Omar Singh','Range Training'],['Yesterday','USER_LOGIN','USR-001','James Dalton','Successful authentication']];return <section className="page"><div className="pageHead"><div><p className="eyebrow">SECURITY & COMPLIANCE</p><h1>Audit Log</h1><p>Immutable record of system access and inventory transactions</p></div></div><div className="panel audit">{events.map((e,i)=><div className="auditRow" key={i}><span className="auditIcon"><ShieldCheck/></span><time>{e[0]}</time><div><b>{e[1]}</b><small>{e[4]}</small></div><code>{e[2]}</code><span>{e[3]}</span></div>)}</div></section>}
export default App;
